CREATE TABLE IF NOT EXISTS USERS (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    login VARCHAR(30) NOT NULL,
    user_name VARCHAR(100) NOT NULL,
    email VARCHAR(40) NOT NULL,
    birthday DATE NOT NULL,
    CONSTRAINT pk_Users PRIMARY KEY (
        user_id
     )
);

CREATE TABLE IF NOT EXISTS FRIENDS (
    user_id BIGINT,
    friend_id BIGINT,
	confirmed BOOLEAN DEFAULT FALSE,
    CONSTRAINT pk_Friends PRIMARY KEY (
        user_id, friend_id
     )
);

CREATE TABLE IF NOT EXISTS FILMS (
    film_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    film_name VARCHAR(100) NOT NULL,
    description VARCHAR(255) NOT NULL,
    release_date DATE NOT NULL,
    duration INTEGER NOT NULL,
    rating_id BIGINT,
    CONSTRAINT pk_Films PRIMARY KEY (
        film_id
     )
);

CREATE TABLE IF NOT EXISTS RATINGS (
    rating_id BIGINT,
    rating_name VARCHAR(10) NOT NULL,
    CONSTRAINT pk_Ratings PRIMARY KEY (
        rating_id
     )
);

CREATE TABLE IF NOT EXISTS LIKES (
    user_id BIGINT,
    film_id BIGINT,
    CONSTRAINT pk_Likes PRIMARY KEY (
        user_id, film_id
     )
);

CREATE TABLE IF NOT EXISTS GENRES (
    genre_id BIGINT,
	genre_name VARCHAR(20) NOT NULL,
    CONSTRAINT pk_Genres PRIMARY KEY (
        genre_id
     )
);

CREATE TABLE IF NOT EXISTS FILM_GENRES (
    film_id BIGINT,
    genre_id BIGINT,
    CONSTRAINT pk_Film_Genres PRIMARY KEY (
        film_id, genre_id
     )
);

ALTER TABLE FRIENDS ADD CONSTRAINT IF NOT EXISTS fk_Friends_user_id FOREIGN KEY(user_id)
REFERENCES USERS (user_id);

ALTER TABLE FRIENDS ADD CONSTRAINT IF NOT EXISTS fk_Friends_friend_id FOREIGN KEY(friend_id)
REFERENCES USERS (user_id);

ALTER TABLE FILMS ADD CONSTRAINT IF NOT EXISTS fk_Films_rating_id FOREIGN KEY(rating_id)
REFERENCES RATINGS (rating_id);

ALTER TABLE LIKES ADD CONSTRAINT IF NOT EXISTS fk_Likes_user_id FOREIGN KEY(user_id)
REFERENCES USERS (user_id);

ALTER TABLE LIKES ADD CONSTRAINT IF NOT EXISTS fk_Likes_film_id FOREIGN KEY(film_id)
REFERENCES FILMS (film_id);

ALTER TABLE FILM_GENRES ADD CONSTRAINT IF NOT EXISTS fk_Film_Genres_film_id FOREIGN KEY(film_id)
REFERENCES FILMS (film_id);

ALTER TABLE FILM_GENRES ADD CONSTRAINT IF NOT EXISTS fk_Film_Genres_genre_id FOREIGN KEY(genre_id)
REFERENCES GENRES (genre_id);

ALTER TABLE FILM_GENRES ADD CONSTRAINT IF NOT EXISTS uk_film_genres_unique UNIQUE (film_id, genre_id);